# Generated by Django 3.0.1 on 2020-01-03 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(choices=[('GV', 'Governance'), ('BG', 'Budget'), ('DC', 'Democracy')], max_length=15)),
                ('cover_photo', models.ImageField(blank=True, default='2016.PNG', upload_to='cover_photos/')),
                ('published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='comment', max_length=50)),
                ('reply_at', models.DateTimeField(auto_now=True)),
                ('reply_body', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Post.Post')),
            ],
            options={
                'ordering': ['-reply_at'],
            },
        ),
    ]
